version: "3.8"

services:
  app:
    image: pjamil/cultivo-api-go:latest
    container_name: cultivo-api-go
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=cultivo-api-go
      - DB_USER=postgres
      - DB_PASSWORD=753951465827PJamil#*
      - VIRTUAL_HOST=cultivo-api.paulojamil.dev.br
      - VIRTUAL_PORT=8080
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - nginx-proxy
      - backend

  db:
    image: postgres:15-alpine
    container_name: cultivo-db
    environment:
      - POSTGRES_DB=cultivo-api-go
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=753951465827PJamil#*
    ports:
      - "5435:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - backend

networks:
  nginx-proxy:
    external: true
  backend:
    driver: bridge

volumes:
  postgres-data:
