version: "3.8"

services:
  app:
    image: pjamil/cultivo-api-go:latest
    container_name: cultivo-api-go
    ports:
      - 8080
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - VIRTUAL_HOST=cultivo-api.paulojamil.dev.br
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=cultivo-api.paulojamil.dev.br
      - LETSENCRYPT_paulojamil@gmail.com=paulojamil@gmail.com
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - default
      - backend

  db:
    image: postgres:15-alpine
    container_name: cultivo-db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4:9.4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pjamil@pjamil.com
      - PGADMIN_DEFAULT_PASSWORD=152535pj
      - VIRTUAL_HOST=pgadmin.paulojamil.dev.br
      - VIRTUAL_PORT=5050
      - LETSENCRYPT_HOST=pgadmin.paulojamil.dev.br
      - LETSENCRYPT_paulojamil@gmail.com=paulojamil@gmail.com
    ports:
      - 5050:80
    depends_on:
      - db
    networks:
      - default
      - backend

networks:
  default:
    name: nginx-proxy
    driver: bridge
    external: true
  backend:
    driver: bridge
    internal: true
    attachable: true

volumes:
  postgres-data:
