version: "3.8"

services:
  app:
    image: pjamil/cultivo-api-go:latest
    container_name: cultivo-api-go
    ports:
      - 8080
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=cultivo-api-go
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - VIRTUAL_HOST=cultivo-api.paulojamil.dev.br
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=cultivo-api.paulojamil.dev.br
      - LETSENCRYPT_paulojamil@gmail.com=paulojamil@gmail.com
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - default
      - backend

  db:
    image: postgres:15-alpine
    container_name: cultivo-db
    environment:
      - POSTGRES_DB=cultivo-api-go
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - backend

networks:
  default:
    name: nginx-proxy
    driver: bridge
    external: true
  backend:
    driver: bridge
    internal: true
    attachable: true
volumes:
  postgres-data:
