version: "3.8"

services:
  app:
    image: pjamil/cultivo-api-go:latest
    container_name: cultivo-api-go
    env_file: .env-prod
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=plant_cultivation
      - DB_PORT=5432
      - VIRTUAL_HOST=cultivo-api.paulojamil.dev.br
      - VIRTUAL_PORT=8080
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - default
      - backend

  db:
    image: postgres:15-alpine
    container_name: cultivo-db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - backend

networks:
  default:
    external: true
  backend:
    driver: bridge

volumes:
  postgres-data:
