version: '3.8'

services:
  db_test:
    image: postgres:15-alpine
    container_name: cultivo-api-go-test-db
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpassword
      - POSTGRES_DB=cultivo_test_db
    ports:
      - "5435:5432" # Porta diferente para evitar conflitos com o DB de desenvolvimento
    volumes:
      - test_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  test_db_data:
