package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// Estagio represents a row from 'public.estagio'.
type Estagio struct {
	ID   int64  `json:"id"`   // id
	Nome string `json:"nome"` // nome
	// xo fields
	_exists, _deleted bool
}

// Exists returns true when the [Estagio] exists in the database.
func (e *Estagio) Exists() bool {
	return e._exists
}

// Deleted returns true when the [Estagio] has been marked for deletion
// from the database.
func (e *Estagio) Deleted() bool {
	return e._deleted
}

// Insert inserts the [Estagio] to the database.
func (e *Estagio) Insert(ctx context.Context, db DB) error {
	switch {
	case e._exists: // already exists
		return logerror(&ErrInsertFailed{ErrAlreadyExists})
	case e._deleted: // deleted
		return logerror(&ErrInsertFailed{ErrMarkedForDeletion})
	}
	// insert (primary key generated and returned by database)
	const sqlstr = `INSERT INTO public.estagio (` +
		`nome` +
		`) VALUES (` +
		`$1` +
		`) RETURNING id`
	// run
	logf(sqlstr, e.Nome)
	if err := db.QueryRowContext(ctx, sqlstr, e.Nome).Scan(&e.ID); err != nil {
		return logerror(err)
	}
	// set exists
	e._exists = true
	return nil
}

// Update updates a [Estagio] in the database.
func (e *Estagio) Update(ctx context.Context, db DB) error {
	switch {
	case !e._exists: // doesn't exist
		return logerror(&ErrUpdateFailed{ErrDoesNotExist})
	case e._deleted: // deleted
		return logerror(&ErrUpdateFailed{ErrMarkedForDeletion})
	}
	// update with composite primary key
	const sqlstr = `UPDATE public.estagio SET ` +
		`nome = $1 ` +
		`WHERE id = $2`
	// run
	logf(sqlstr, e.Nome, e.ID)
	if _, err := db.ExecContext(ctx, sqlstr, e.Nome, e.ID); err != nil {
		return logerror(err)
	}
	return nil
}

// Save saves the [Estagio] to the database.
func (e *Estagio) Save(ctx context.Context, db DB) error {
	if e.Exists() {
		return e.Update(ctx, db)
	}
	return e.Insert(ctx, db)
}

// Upsert performs an upsert for [Estagio].
func (e *Estagio) Upsert(ctx context.Context, db DB) error {
	switch {
	case e._deleted: // deleted
		return logerror(&ErrUpsertFailed{ErrMarkedForDeletion})
	}
	// upsert
	const sqlstr = `INSERT INTO public.estagio (` +
		`id, nome` +
		`) VALUES (` +
		`$1, $2` +
		`)` +
		` ON CONFLICT (id) DO ` +
		`UPDATE SET ` +
		`nome = EXCLUDED.nome `
	// run
	logf(sqlstr, e.ID, e.Nome)
	if _, err := db.ExecContext(ctx, sqlstr, e.ID, e.Nome); err != nil {
		return logerror(err)
	}
	// set exists
	e._exists = true
	return nil
}

// Delete deletes the [Estagio] from the database.
func (e *Estagio) Delete(ctx context.Context, db DB) error {
	switch {
	case !e._exists: // doesn't exist
		return nil
	case e._deleted: // deleted
		return nil
	}
	// delete with single primary key
	const sqlstr = `DELETE FROM public.estagio ` +
		`WHERE id = $1`
	// run
	logf(sqlstr, e.ID)
	if _, err := db.ExecContext(ctx, sqlstr, e.ID); err != nil {
		return logerror(err)
	}
	// set deleted
	e._deleted = true
	return nil
}

// EstagioByID retrieves a row from 'public.estagio' as a [Estagio].
//
// Generated from index 'estagio_pk'.
func EstagioByID(ctx context.Context, db DB, id int64) (*Estagio, error) {
	// query
	const sqlstr = `SELECT ` +
		`id, nome ` +
		`FROM public.estagio ` +
		`WHERE id = $1`
	// run
	logf(sqlstr, id)
	e := Estagio{
		_exists: true,
	}
	if err := db.QueryRowContext(ctx, sqlstr, id).Scan(&e.ID, &e.Nome); err != nil {
		return nil, logerror(err)
	}
	return &e, nil
}

// EstagioByNome retrieves a row from 'public.estagio' as a [Estagio].
//
// Generated from index 'estagio_unique'.
func EstagioByNome(ctx context.Context, db DB, nome string) (*Estagio, error) {
	// query
	const sqlstr = `SELECT ` +
		`id, nome ` +
		`FROM public.estagio ` +
		`WHERE nome = $1`
	// run
	logf(sqlstr, nome)
	e := Estagio{
		_exists: true,
	}
	if err := db.QueryRowContext(ctx, sqlstr, nome).Scan(&e.ID, &e.Nome); err != nil {
		return nil, logerror(err)
	}
	return &e, nil
}
